Pick-px/frontend

src/components/PixelCanvas.tsx

- 512 * 512 범위 내에 없다면 시점 이동 발생하지 않도록 예외처리 완료.
- 메인에 푸시된 socket 통신 로직 반영

[FEAT]: 픽셀 클릭시 ViewPort 가운데로 이동 기능 추가

---

src/components/PixelCanvas.tsx

- 리팩토링 코드로 통합
- 사라졌던 선택한 픽셀 뷰포트 가운데로 위치하는 기능 centerOnPixel 추가하였습니다

SCRUM-22: 리팩토링 코드 통합 및 선택 픽셀 중앙위치 기능 추가

---

src/App.tsx
src/components/CanvasUI.tsx
src/components/PixelCanvas.tsx

- preview canvas 만듦
- 팔레트 색상 선택시 preview canvas에 미리반영
- 확정 버튼 누르면 preview canvas에 4초간 유지

SCRUM-20: preview canvas & confirm drawing & preview drawing

---

src/components/CanvasUI.tsx
src/components/modal/CanvasModalContent.tsx
src/store/modalStore.ts

- 각 버튼별 상태 Zustand로 관리 진행
- 드롭다운 버튼 추가 및 UI 수정

SCRUM-37 :[FEAT] 측면 드롭다운 버튼 UI 구현

---

package-lock.json
package.json
src/auth/AuthCallbackPage.tsx
src/main.tsx
src/router/router.tsx
src/services/apiClient.ts
src/services/authService.ts

- react-router-dom 추가 하여 라우팅 진행
- OAuth callback 로직 프론트엔드로 이전

SCURM-43:[FIX]OAuth 로직 수정

---

src/services/apiClient.ts

- apiClient.ts의 baseURL을 서버 로컬 호스트 주소로 수정하였습니다

SCRUM-45:[FIX]baseURL 수정"

---

src/App.tsx
src/components/PixelCanvas.tsx
src/router/router.tsx
src/services/socketService.ts

[SCRUM-53] api 요청 및 수신 / 소켓 연결

---

.github/workflows/deploy.yml
src/components/PixelCanvas.tsx
src/hooks/useSocket.ts
src/services/apiClient.ts
src/services/authService.ts
src/services/socketService.ts

🛠️ CI/CD 적용을 위한 github action workflow 파일을 생성하였습니다.
- main branch에 pr을 생성하면 빌드 테스트를 진행하게 세팅하였습니다.
- 실제 main branch에 반영시 자동으로 새로운 build파일로 S3에 배포, cloudFront를 통해 배포된 서버와 통신하게 구현하였습니다.
🚀 localhost로 세팅되어있던 url 배포용 url로 수정하였습니다.
- 로컬에서 테스트가 필요하시면 .env 환경변수 세팅 노션을 참고해주세요
🔨캔버스 아이디 조회시 중첩으로 소켓 연결하는 문제를 해결하였습니다.
-  /api까지 포함되는 url을 수정하였습니다.

[SCRUM-44] github action workflow생성 및 배포용 환경변수 url 세팅

---

src/auth/AuthCallbackPage.tsx
src/components/PixelCanvas.tsx
src/components/Preloader.tsx
src/components/chat/ChatAPI.tsx

- /api/canvas/pixels 에서 응답을 다 받아오기 전에 표출할 Preloader 페이지 추가
- 로그인시 callback 호출할때 역시 Preloader 페이지 렌더링

SCRUM-82:[FEAT] preloader 페이지 추가

---

src/services/apiClient.ts

SCURM-83:[FIX] AT 재발급 로직 수정

---

src/components/CanvasUI.tsx

그룹 버튼 클릭시 로그인 체크 후 띄울 수 있게 수정하였습니다.

[SCRUM-85] 그룹 모달 로그인 체크 로직 추가

---

src/App.tsx
src/components/modal/MyPageModalContent.tsx
src/services/apiClient.ts
src/store/modalStore.ts

- 토큰 갱신시 본문이 아닌 헤더에서 AT 가져오도록 수정
- 마이페이지에서 로그인시 받는 user 가 아닌 api 요청하여 받는 userInfo 에서만 받는 것으로 수정
- 모달 중복 현상 수정

SCRUM-90:[FIX]마이페이지 수정 및 모달 중복 open 현상 수정

---

package-lock.json
package.json
src/App.tsx
src/auth/AuthCallbackPage.tsx
src/components/PixelCanvas.tsx
src/components/chat/Chat.tsx
src/services/authService.ts

- 채팅장 제목은 15자, 그룹 탭은 10자 이상 넘으면 ... 으로 처리했습니다(ellipsis)
- 시점 이동 우클릭시 브라우저 기본동작이 적용되어서 이를 수정하였습니다

[SCRUM-97]: 채팅창 UI 수정 및 우클릭 이벤트 수정

---

src/components/Preloader.tsx
src/services/apiClient.ts
src/services/authService.ts

[SCRUM-101]:apiClients 훅 호출 규칙 위반 수정

---

src/api/GroupAPI.tsx
src/components/group/GroupCreateTab.tsx
src/components/group/GroupJoinTab.tsx
src/components/group/GroupListTab.tsx
src/components/modal/GroupModalContent.tsx
src/components/modal/Modal.tsx

Revert "[SCRUM-96] 그룹 모달 검증 및 오류 수정"

---

src/components/chat/Chat.tsx

로그인 상태에서만 채팅창을 열 수 있도록 수정하였습니다.

[SCRUM-104] login-chatopen

---

src/components/modal/MyPageModalContent.tsx
src/services/myPageService.ts

[SCRUM-105]: 마이페이지 데이터 적용

---

src/auth/AuthCallbackPage.tsx
src/components/modal/LoginModalContent.tsx

- 로그인 시 현재 경로 저장: 사용자가 로그인 버튼을 클릭할 때, 현재 페이지의 URL 경로를
sessionStorage에 저장하도록 LoginModalContent.tsx 파일을 수정했습니다.
- 로그인 완료 후 저장된 경로로 이동: OAuth 인증이 성공적으로 완료되면,
AuthCallbackPage.tsx에서 sessionStorage에 저장된 경로를 읽어와 해당 경로로
리디렉션합니다. 만약 저장된 경로가 없으면 기본적으로 홈페이지(/)로 이동합니다.

[SCRUM-107]: 로그인시 Navigate 에 canvas_id 반영

---

src/api/GroupAPI.tsx
src/components/group/GroupCreateTab.tsx
src/components/group/GroupJoinTab.tsx
src/components/group/GroupListTab.tsx
src/components/modal/GroupModalContent.tsx
src/components/modal/Modal.tsx

그룹 조인시 매개변수 추가
- canvas_id
그룹 모달 및 Modal 컴포넌트 ui 수정
- 그룹 모달 내용에 따라 height 조절 애니메이션 추가
그룹 목록과 참여 신청 목록에서 채팅용 그룹 표시 제외
- is_default 변수를 사용하여 필터링하여 목록 출력
develop 브랜치 내용을 갱신하는 과정에서 오류가 발생해 해결하는 과정에서 중복 커밋이 적용되었습니다.
1.  git pull origin develop으로 feature 브랜치에 직접 병합하는 과정에서 오류 발생
- 깃 히스토리가 다르지 않다면 잘 적용되지만 히스토리가 다를경우 병합에 실패하게 됩니다.
2. git pull --rebase로 히스토리를 정리하여 시도하였으나 실패
- 이때 rebase는 커밋 해시값을 새로 생성하여 현재 브랜치의 커밋을 새로 생성하게 됨.
- 해당 과정으로 인해 같은 내용의 커밋이 다른 해시값으로 추가되어 중복되었습니다.
3. 이후 git merge --no-ff 명령어를 통해 현재까지의 히스토리를 커밋으로 남기는 merge로 push가 안되는 오류를 해결하였습니다.

[SCRUM-96] 그룹 모달 검증 및 오류 수정

---

src/App.tsx
src/components/PixelCanvas.tsx

- 로딩 시, 메뉴 버튼 및 채팅버튼을 숨김 처리하였습니다.
- 로딩 후 캔버스가 확대되는 애니메이션을 추가하였습니다.
- 쿨다운 중일 때 화면 테두리에 빨간색을 나타내게 하였습니다.
- 캔버스 테두리 수정하였습니다.

[SCRUM-110] loading hide icon and animation

---

src/components/chat/Chat.tsx

- 그룹 모달창 열 때 채팅창이 닫기도록 수정하였습니다.

[SCRUM-112] groupmodal-open-hide-chat

---

src/components/canvas/PixelCanvas.tsx

[SCRUM-138] mobile-canvas-size

---

src/api/canvasFetch.ts
src/components/canvas/PixelCanvas.tsx
src/components/modal/CanvasModalContent.tsx
src/components/toast/InstructionsToast.tsx
src/hooks/useSocket.ts

SCRUM-139:좌클릭 드래그로 수정

---

src/components/canvas/PixelCanvas.tsx
src/components/canvas/canvasConstants.ts

- 모바일 환경에서 한 손가락 터치 드래그로 캔버스 패닝이 가능하도록  개선하여 PC 마우스 드래그와 유사하게 수정
- 캔버스 초기 배율 설정 로직 변경

[SCRUM-140] mobile-touch

---

src/components/canvas/CanvasUI.tsx
src/components/canvas/CanvasUIMobile.tsx
src/components/canvas/PixelCanvas.tsx
src/components/toast/InstructionsToast.tsx
src/hooks/useSocket.ts

- 모바일에서 확대축소 버튼을 추가하였습니다.
- 게임 설명 모달창을 수정하였습니다.

[SCRUM-140] mobile-touch-zoom

---

src/components/canvas/PixelCanvas.test.tsx
src/components/canvas/PixelCanvas.tsx
src/components/chat/MessageItem.tsx
src/setupTests.ts
src/store/canvasUiStore.ts
vitest.config.ts

- centerOnWorldPixel 추가하여 채팅메시지의 (x,y) 입력시 해당 좌표로 시점 이동합니다.
- PixelCanvas 렌더링 시간 테스트 코드 추가하였습니다( **npx vitest** 명령어를 통해 실행 가능합니다.)

[SCRUM-141]:채팅 메시지(x,y) 입력시 해당 픽셀로 시점 이동 기능

---

src/components/modal/CanvasModalContent.tsx
src/services/socketService.ts

- <ins> 캔버스 이동 시 새로고침 하도록 수정하였습니다. </ins>
- 소켓 이벤트 명 수정.

[SCRUM-142] canvas-movement-refresh

---

src/components/canvas/PixelCanvas.tsx

- 이미지 모드에서 캔버스가 재정렬되는 에러를 수정하였습니다.

[SCRUM-122] imagemode-error

---

src/components/canvas/CanvasUIPC.tsx
src/components/canvas/PixelCanvas.tsx

- 이미지 첨부 후, 편집 시 캔버스 내 그리드가 나타나도록 수정하였습니다.

[SCRUM-150] image-edit-canvas-grid

---

src/components/canvas/PixelCanvas.tsx
src/hooks/useCanvasInteraction.ts

- 픽셀 확정 버튼을 누르면, 쿨다운 상태 동안 빨간색 테두리 깜빡임 효과.
- 이전 확정 픽셀을 알수있도록 함.

[SCRUM-156] cooldown-pixel-flash

---

src/api/CanvasAPI.ts
src/components/modal/CanvasModalContent.tsx

- 캔버스 모달에 이벤트 시작여부에 따라 다르게 표시하였습니다

[SCRUM-160]캔버스 started_at 반영하여 캔버스 이동 모달에 반영

---

src/api/canvasFetch.ts
src/components/canvas/CanvasUIMobile.tsx
src/components/canvas/PixelCanvas.tsx

- canvasFetch.ts 에서 api 요청을 보내어 type과 endAt을 가져옵니다
- 이후 이를 setTimeout을 활용하여 타이머를 구현하였습니다.

[SCURM-162]이벤트 캔버스 타이머 구현

---

index.html
package.json
src/components/canvas/CanvasUIMobile.tsx
src/components/canvas/CanvasUIPC.tsx

[SCRUM-168] 확정 버튼 아이콘 변경

---

src/components/SocketIntegration.tsx
src/components/canvas/PixelCanvas.tsx
src/components/chat/Chat.tsx
src/components/chat/ChatAPI.tsx
src/hooks/useCanvasInteraction.ts
src/hooks/useChatSocket.ts
src/services/socketService.ts
src/store/chatStore.ts

- 방장만 이미지 업로드 가능, 일반 사용자는 동기화 버튼으로 이미지 표시
- 전체 채팅방에서는 이미지 업로드/동기화 버튼 비활성화
1. 이미지 업로드 및 공유 시스템
- 방장(leader)만 이미지 업로드 가능
- 업로드된 이미지는 소켓을 통해 그룹 멤버들에게 전송
- 이미지 위치, 크기 정보도 함께 전송하여 모든 사용자가 동일한 뷰 공유
2. 동기화 메커니즘
- 사용자가 채팅방에 입장해도 자동으로 이미지가 표시되지 않음
- 동기화 버튼을 클릭해야 이미지가 표시됨
- 동기화 상태(isSyncEnabled)에 따라 이미지 표시 여부 결정

[SCRUM-161] group overlay

---

src/components/canvas/CanvasUIMobile.tsx
src/components/canvas/CanvasUIPC.tsx
src/components/toast/InstructionsToast.tsx
src/index.css

- 모바일
- 이미지 업로드 버튼 추가 및 위치 이동
- 컬러 피커 기본 제공 활용 및 확정 버튼 이동(모바일에서는 팔레트가 없음)
- PC 
- 이미지 업로드 버튼 위치 이동
- 팔레트에 (x,y) 좌표 표출 및 colorpicker 이동

SCRUM-174]: PC 버전 및 UI 이동

---

src/App.tsx
src/components/canvas/GameCanvas.tsx
src/components/canvas/GameStarfieldCanvas.tsx
src/hooks/useCanvasInteraction.ts
src/hooks/useGameSocket.ts
src/services/socketService.ts
src/utils/canvasTypeUtils.ts

- 일반 캔버스와 게임 캔버스를 분기하였습니다.
- 게임 모드에서는 채팅 컴포넌트 비활성화 / 메뉴 버튼 비활성화
- 전체 구조 및 흐름 틀만 작성된 상태로, 로직 보완 필요
아직 완성된 상태는 아니며, 기본 틀만 잡아둔 상태입니다.
세부 보완은 추가 작업 예정입니다.
구조나 방향에 대한 피드백이 있다면 말씀해주시면 감사하겠습니다 !

[SCRUM-173] gamecanvas-separation

---

src/components/canvas/GameCanvas.tsx
src/components/canvas/PixelCanvas.tsx

- 참고) 현재는 canvas_id 가 3인 캔버스를 게임 모드로 고정시킨 상태입니다. 
- 게임모드 캔버스를 만들 때 사이즈 10*10으로 부탁드립니다. 
- 테스트 시 편의성을 위해 좌측 상단에 나가기 버튼을 미리 추가하였습니다.

[SCRUM-182] game-exit

---

src/App.tsx
src/components/canvas/PixelCanvas.tsx
src/components/modal/CanvasEndedModal.tsx
src/store/modalStore.ts

- 이벤트 캔버스 종료시 메인으로 이동 버튼 띄우는 모달 추가하였습니다.

[SCRUM-187]:이벤트 모드 종료시 메인화면 이동 모달 추가

---

src/App.tsx
src/api/CanvasAPI.ts
src/api/canvasFetch.ts
src/components/canvas/CanvasUI.tsx
src/components/canvas/CanvasUIMobile.tsx
src/components/canvas/CanvasUIPC.tsx
src/components/canvas/PixelCanvas.tsx
src/components/game/GameCanvas.tsx
src/components/game/GameStarfieldCanvas.tsx
src/components/game/GameTimer.tsx
src/utils/canvasTypeUtils.ts
tsconfig.app.json
tsconfig.node.json

[SCRUM-190] 게임 타이머 컴포넌트, 흑백모드 추가

---

src/components/canvas/CanvasUIPC.tsx
src/components/canvas/UserCount.tsx
src/services/socketService.ts

- useEffect로 해당 소켓 이벤트 함수가 실행되거나, canvas_id간 이동할때 접속자 수 표시 컴포넌트 재렌더링되게 구현하였습니다.

[SCRUM-180] 접속자수 표시 기능 구현

---

src/components/canvas/canvasConstants.ts
src/components/modal/CanvasModalContent.tsx

- 상시 / 게임 / 이벤트로 세분화 하였습니다. 
-

[SCRUM-207]: CanvasModalContent 세분화

---

src/components/canvas/CanvasUIPC.tsx
src/components/gameSocketIntegration.tsx
src/components/modal/CanvasModalContent.tsx
src/components/modal/MyPageModalContent.tsx

- 캔버스 이동 모달 캔버스 개수 표시 삭제
- 마이페이지 종료 태그 삭제, ui 시도, 참여 표시 수정
- props 타입 명시 오류 해결
- 버튼 호버시 명칭 앨범 -> 갤러리로 변경

[Fix] 캔버스 이동 모달, 마이페이지 모달 데이터 표시 UI 개선

---

src/components/game/GameCanvas.tsx
src/components/modal/QuestionModal.tsx

- 게임 엔터 방지하였습니다.
- 답안 선택 안했을 시, 오답 처리하였습니다.

[SCRUM-215] game-fail

---

src/components/game/GameCanvas.tsx

- 이미 색칠된 영역에 같은 색으로 다시 칠하려고 할 경우, "이미 칠해진 색상입니다" 알림을 띄우도록 처리했습니다.
- 문제를 선택하지 않은 채 제한 시간이 초과되면, 자동 오답 처리와 함께 안내 알림창이 표시됩니다.

[SCRUM-217] duplicate-coloring

---

src/components/game/GameCanvas.tsx
src/components/game/LifeIndicator.tsx

- 생명 컴포넌트를 분리하였습니다.
- 생명이 차감될 때 메시지 및 애니메이션을 추가하였습니다.

[SCRUM-223] life-indicator

---

src/components/canvas/CanvasUIPC.tsx
src/services/authService.ts

[SCRUM-224]:게스트 로그인 

---

src/components/canvas/PixelCanvas.tsx

[feat] cooldown-3

---

index.html
src/components/canvas/PixelCanvas.tsx
src/components/canvas/StarfieldCanvas.tsx
src/setupTests.ts
src/utils/ImageEditorUI.tsx
src/utils/canvasDrawing.ts
src/utils/starfieldUtils.ts

PixelCanvas 컴포넌트의 렌더링 성능을 개선하고 코드 구조를 명확하게 하기 위해 리팩토링을 진행했습니다.
기존에는 cooldown 등의 애니메이션 효과가 발생할 때마다 무거운 draw 함수가 매 프레임 호출되어, 많은 요청이 있을 경우 렌더링 지연 및 CPU 사용량 증가의 원인이 되었습니다.
이번 리팩토링은 렌더링 로직을 여러 레이어로 분리하고, 컴포넌트와 유틸리티 함수를 분리하여 이 문제를 해결하고 코드의 가독성과 유지보수성을 높이는 데 중점을 두었습니다.
draw 함수 분리: 기존의 거대한 draw 함수를 아래와 같이 3개의 목적별 함수로 분리했습니다.
- drawBaseLayer(): 캔버스 배경, 픽셀 데이터 등 정적인 요소를 그립니다.
- drawImageLayer(): 사용자가 첨부한 이미지와 관련 UI(테두리, 핸들)를 그립니다.
- drawPreviewLayer(): 마우스 오버, 픽셀 깜빡임 등 매 프레임 변경이 필요한 동적인 요소만 그립니다.
- requestAnimationFrame 최적화: 애니메이션 루프(useEffect)에서는 가장 가벼운 drawPreviewLayer 함수만 호출하도록 변경했습니다. 이로 인해 애니메이션 중 발생하는 불필요한 전체 리렌더링을 방지하여 CPU 부하를 크게 줄였습니다.
- drawAll() 도입: 줌, 이동 등 전체 캔버스를 다시 그려야 할 때만 호출되는 drawAll 함수를 새로 만들어 명시적으로 전체 업데이트를 관리합니다.
ImageEditorUI 컴포넌트 신규 생성: PixelCanvas 내부에 복잡하게 얽혀있던 이미지 편집 관련 …

[SRCUM-228]]PixelCanvas.tsx 렌더링 로직 분리

---

src/components/modal/DeathModal.tsx

- 탈락 후 관전모드를 추가하였습니다.
- 탈락 메시지가 3초간 띄워지고, 이후 투명도를 높여 게임을 지켜볼 수 있도록 수정

[SCRUM-218] fail-watching

---

src/components/game/GameCanvas.tsx

hasError를 체크하고 404페이지를 반환하는 조건의 위치가 useCallback보다 위에 있어 리액트 훅 규칙을 위반하는 오류를 수정하였습니다.

[SCRUM-230] gamemode 404 error

---

src/App.tsx
src/api/AdminAPI.ts
src/auth/AuthCallbackPage.tsx
src/components/modal/MyPageModalContent.tsx
src/pages/admin/AdminDashboard.tsx
src/pages/admin/CanvasManagement.tsx
src/router/router.tsx
src/services/authService.ts
src/store/authStrore.ts

- user에 role을 추가하였습니다.
- role 이 'admin'일 때, 마이페이지에 관리자 페이지를 추가하였습니다.
- 관리자 페이지는 추후 명세서에 맞게 수정 예정입니다.

[SCRUM-240] admin-page

---

src/components/game/GameCanvas.tsx

- PC 버전에서만 좌측 하단에 BGM 끄기/켜기 버튼이 나타납니다.

[SCRUM-241] 게임내 BGM 켜기/끄기 버튼 추가

---

src/api/AdminAPI.ts
src/components/modal/CanvasModalContent.tsx
src/index.css
src/pages/admin/AdminDashboard.tsx
src/pages/admin/CanvasManagement.tsx

관리자 페이지 추가

---

src/components/canvas/CanvasUIPC.tsx
src/components/canvas/UserCount.tsx
src/components/modal/MyPageModalContent.tsx

- 전체 접속자 수, 캔버스별 접속자 수 마우스 호버시 툴팁 기능 추가하였습니다.
- 도움말 버튼 위치를 메뉴 토글버튼 안에서 옆으로 변경하였습니다.
- 마이페이지 집계중 표시에서 스피너를 제거하였습니다.

[Fix] 접속자수 툴팁 추가 및 도움말 버튼 위치 수정

---

src/components/game/GameReadyModal.tsx

- 게임 대기창을 수정하였습니다.
- 게임 방법을 추가하였습니다.

[SCRUM-254] game-ready

---

src/components/canvas/CanvasUIMobile.tsx
src/components/chat/Chat.tsx
src/hooks/useSocket.ts

- 메뉴 아이콘 형식에서 사이드바로 변경
- 채팅창 밖 영역 클릭시 닫히도록 변경
- 투명도 조절 슬라이드 가능토록 변경

[SCRUM-257] 모바일 UI 사이드바, 채팅창 밖 영역 클릭시 닫기 적용

---

src/App.tsx
src/components/game/GameReadyModal.tsx
src/components/modal/GameAlertModal.tsx
src/hooks/useSocket.ts
src/store/modalStore.ts

- 게임 시작 30초 전 공지를 토스트에서 모달창으로 수정하였습니다.
- 모바일에서 게임 준비창을 크기에 맞게 수정하였습니다. (스크롤 가능)

[SCRUM-256] game-notice
